# -*- coding: utf-8 -*-
"""lecture1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g4Grf26bW531921yDg9EC-dubyVWWkd6
"""

# Variables
var1 = 10 # integer
var2 = 25
today = "Friday"
var3 = 10.0 # float 
print(var3)
variable_type = type(var3)
print(variable_type)

# Strings
s = "Today is Friday"
variable_type = type(s)
print(s)
print(variable_type)

var1 = "ankara"
var2 = "ist"
var3 = var1+var2
print(var3)

var4 = "100"
var5 = "200"
var6 = var4+var5
length = len(var6) 
print(length)

# numbers
integers = -60
floats = -40.5

# built in functions
float1 = 50.5
to_integer = int(float1)
print(to_integer)

float2 = 40.6
rounding = round(float2)
print(rounding)

# Functions
var1 = 20
var2 = 50

def func(a,b):
   output = (((a+b)*50)/100.0)*a/b
   return output

answer = func(var1,var2)
print(answer)

def printing():
  print("This is BAU")
printing()

# Lambda functions
x = 5
output = lambda x:x*x
print(output(x))

# lists 
list1 = [1,2,3,4,5,6]
type(list1)

list_str = ["Sunday","Monday","Tuesday"]
type(list_str)

list1 = [1,2,3,4,5,6]
value = list1[1]
print(value)

last_value = list1[-1]
print(last_value)

list_divide = list1[0:3]
print(list_divide)
list1.append(7)
print(list1)
list1.remove(7)
print(list1)
list1.reverse()
print(list1)

list2 = [1,5,4,3,6,7,2]
list2.sort()
print(list2)

mixed_list = [1,2,3,"aa","bb"]
print(mixed_list)

# Tuple
t = (1,2,3,3,4,5,5,6)

print(t.count(5))
print(t.index(5))

# Dictionary
dictionary = {"ali":32,"veli":45,"ayse":13}
print(dictionary)
# ali ,veli ,ayse = keys
# 32,45,13 = values

var_two = 5
print(var_two)

#Conditionals
var1 = 10
var2 = 20

if(var1 > var2):
    print("var1 is greater than var2")
elif(var1 == var2):
    print("var1 and var2 are equal")
else:
    print("var1 is less than var2")

list1 = [1,2,3,4,5]

value = 9
if value in list1:
    print(" {} is in the list".format(value))
else:
    print("{} is  not in the list".format(value))

# Loops
for each in range(1,11):
    print(each)

for each in "ankara ist":
    print(each)

for each in "ankara ist".split(): 
    print(each)

list1 = [1,4,5,6,8,3,3,4,67]
 
counter = 0
for each in list1:
    counter = counter + each
print(counter)
summation = sum(list1)
print(summation)

# while loop
    
i = 0
while(i <4):
  print(i)
  i = i + 1

list1 = [1,4,5,6,8,3,3,4,67]
length = len(list1)   
each = 0
count = 0
while(each < length):
    count = count + list1[each]
    each = each + 1 
print(count)